# Chapter 5 - Alpha diversity

## 5.1 - Load MG data

```{r load_mg_data, warning = FALSE, comments = "", message = FALSE, eval = FALSE}
load("data/data_mg.Rdata")
```


## 5.2 - Hill numbers

### Calculate alpha diversity

```{r alpha_div, comment = "", message = FALSE, warning = FALSE}
# Neutral
neutral <-
  mag_weighted %>% 
  dplyr::select(where(~ !all(. == 0))) %>% 
  hilldiv(., q = 1) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(neutral = 1) %>%
  rownames_to_column(var = "animal_code")

# Phylogenetic
phylogenetic <-
  mag_weighted %>% 
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1, tree = genome_tree) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(phylogenetic = 1) %>%
  rownames_to_column(var = "animal_code")

# Functional KEGG
dist_kegg <-
  genome_kegg_paths %>%
  column_to_rownames(var = "genome") %>%
  traits2dist(., method = "gower")

functional_kegg <-
  mag_weighted %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1 , dis = dist_kegg) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(functional_kegg = 1) %>%
  rownames_to_column(var = "animal_code") %>%
  mutate(functional_kegg = if_else(is.nan(functional_kegg), 1, functional_kegg))

# Sequence depth
log_seq_depth <-
  read_counts %>%
  column_to_rownames(var = 'genome') %>%  
  {as.data.frame(log(colSums(.)))} %>%
  rename(seq_depth = 'log(colSums(.))') %>%
  rownames_to_column(var = 'animal_code')

# Merge all metrics
alpha_div <-
  neutral %>%
  full_join(phylogenetic, by = 'animal_code') %>%
  full_join(functional_kegg, by = 'animal_code') %>%
  left_join(chicken_metadata, by = 'animal_code') %>%
  left_join(log_seq_depth, by = 'animal_code')
```

### Save data

```{r save_alpha, comment = "", echo = FALSE, message = FALSE, warning = FALSE, eval = FALSE}
save(alpha_div, file = "data/alpha_div.Rdata")
```

### Alpha diversity by sampling day (Fig. 1e)

```{r plot_div, comment = "", message = FALSE, warning = FALSE, fig.height = 4, fig.width = 12, fig.fullwidth = TRUE}
# Neutral
p_n <- 
  ggplot(alpha_div,
         aes(x = sampling_time,
         y = neutral,
         group = sampling_time,
         colour = sampling_time)) +
  geom_boxplot(aes_string(colour = 'sampling_time', fill = 'sampling_time'),
               width = 0.3,
               lwd = 3,
               outlier.color = NA,
               position = position_nudge(x = -.4)
               ) +
  ylim(200,600) +
  geom_jitter(width = 0.15, alpha = 0.6) +
  stat_summary(geom = 'crossbar',
               width = 0.3,
               fatten = 0,
               color = 'white',
               position = position_nudge(x = -.4),
               fun.data = function(x){ return(c(y = median(x),
                                                ymin = median(x),
                                                ymax = median(x))
               ) }) +
  scale_fill_manual(values = c('#E69F00', '#CC6677', '#56B4E9')) +
  scale_color_manual(values = c('#E69F00', '#CC6677', '#56B4E9')) +
  theme_minimal() +
  ggtitle("Neutral diversity") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "none")

# Phylogenetic
p_p <- 
  ggplot(alpha_div,
  aes(x = sampling_time,
      y = phylogenetic,
      group = sampling_time,
      colour = sampling_time)) +
  geom_boxplot(aes_string(colour = 'sampling_time', fill = 'sampling_time'),
               width = 0.3,
               lwd = 3,
               outlier.color = NA,
               position = position_nudge(x = -.4)
               ) +
  ylim(9,21) +
  geom_jitter(width = 0.15, alpha = 0.6) +
  stat_summary(geom = "crossbar",
               width = 0.3,
               fatten = 0,
               color = "white",
               position = position_nudge(x = -.4),
               fun.data = function(x){ return(c(y = median(x),
                                                ymin = median(x),
                                                ymax = median(x))
               ) }) +
  scale_fill_manual(values = c('#E69F00', '#CC6677', '#56B4E9')) +
  scale_color_manual(values = c('#E69F00', '#CC6677', '#56B4E9')) +
  theme_minimal() + ylab("Effective number of strains") +
  ggtitle("Phylogenetic diversity") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = 'none')

# Functional KEGGs
p_f_kegg <-
  ggplot(alpha_div,
         aes(x = sampling_time,
         y = functional_kegg,
         group = sampling_time,
         colour = sampling_time)) +
  geom_boxplot(aes_string(colour = 'sampling_time', fill = 'sampling_time'),
               width = 0.3,
               lwd = 3,
               outlier.color = NA,
               position = position_nudge(x = -.4)
  ) +
  ylim(1.30,1.50) +
  geom_jitter(width = 0.15, alpha = 0.6) +
  stat_summary(geom = "crossbar",
               width = 0.3,
               fatten = 0,
               color = "white",
               position = position_nudge(x = -.4),
               fun.data = function(x){ return(c(y = median(x),
                                                ymin = median(x),
                                                ymax = median(x))
               ) }) +
  scale_fill_manual(values = c("#E69F00", "#CC6677", "#56B4E9")) +
  scale_color_manual(values = c("#E69F00", "#CC6677", "#56B4E9")) +
  theme_minimal() + ylab("Effective number of strains") +
  ggtitle("Functional diversity KEGG") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "none")

grid.arrange(p_n, p_p, p_f_kegg, ncol = 3)
```


## 5.3 - Temporal development (Supplementary Table S2)

### Neutral

```{r}
m_div_n <-
  lme(neutral ~ seq_depth + sex + breed + treatment + trial * age,
      random = ~1|pen,
      data = alpha_div)
summary(m_div_n)
```

### Phylogenetic

```{r}
m_div_p <-
  lme(phylogenetic ~ seq_depth + sex + breed + treatment + trial * age,
      random = ~ 1|pen,
      data = alpha_div)
summary(m_div_p)
```

### Functional KEGG

```{r}
m_div_f_kegg <-
  lme(functional_kegg ~ seq_depth + sex + breed + treatment + trial * age,
      random = ~ 1|pen,
      data = alpha_div)
summary(m_div_f_kegg)
```


### Clean environment

```{r clean_environment, comment = "", message = FALSE, warning = FALSE}
rm(list = ls())
```
