# Chapter 7 - Bacterial temporal trends

## 7.1 - Load MG data

```{r load_data_mag_trends, message = FALSE, warning = FALSE, echo = FALSE}
load("data/data_mg.Rdata")
```

## 7.2 - Temporal trends related to MCI (Fig. 2c)

### Calculate t-SNE based on GIFTs

```{r tsne_temp, comment = "", message = FALSE, warning = FALSE}
set.seed(100)
tsne_func <- Rtsne(X = gifts_elements, dims = 2, check_duplicates = FALSE)

genome_taxonomy <- 
  genome_taxonomy %>% 
  mutate(avg_mci = rowMeans(gifts_elements)) %>% 
  mutate(length = genome_stats$mag_length)

tsne_df <-
  tsne_func$Y %>%
  as.data.frame() %>%
  mutate(genome = rownames(gifts_elements)) %>%
  left_join(genome_taxonomy, by = 'genome') %>%
  mutate_at(vars(phylum, class, order, family), factor) %>%
  mutate(order = factor(order, levels = names(order_colors))) %>%
  mutate(phylum = factor(phylum, levels = names(phylum_colors))) %>%
  rename(tsne1 = 'V1', tsne2 = 'V2')
```

### Divide relative abundances by sampling time 

```{r filter_data_by_day, comment = "", message = FALSE, warning = FALSE}
# Day 7
met_d7 <- 
  chicken_metadata %>% 
  filter(sampling_time == 7) 

abun_d7 <-  
  hel %>% 
  t() %>% 
  as.data.frame() %>% 
  filter(rownames(.) %in% met_d7$animal_code) %>% 
  summarise(across(everything(), mean, na.rm = TRUE)) %>% 
  t() %>% 
  as.data.frame() %>% 
  rename(abundance = 'V1') %>% 
  rownames_to_column('genome')

# Day 21
met_d21 <- 
  chicken_metadata %>% 
  filter(sampling_time == 21) 

abun_d21 <-  
  hel %>% 
  t() %>% 
  as.data.frame() %>% 
  filter(rownames(.) %in% met_d21$animal_code) %>% 
  summarise(across(everything(), mean, na.rm = TRUE)) %>% 
  t() %>% 
  as.data.frame() %>% 
  rename(abundance = 'V1') %>% 
  rownames_to_column('genome')

# Day 35
met_d35 <- 
  chicken_metadata %>% 
  filter(sampling_time == 35)

abun_d35 <-  
  hel %>% 
  t() %>% 
  as.data.frame() %>% 
  filter(rownames(.) %in% met_d35$animal_code) %>% 
  summarise(across(everything(), mean, na.rm = TRUE)) %>% 
  t() %>% 
  as.data.frame() %>% 
  rename(abundance = 'V1') %>% 
  rownames_to_column('genome')
```

### Plot t-SNE

```{r plot_tsne_by_day, comment = "", message = FALSE, warning = FALSE, fig.height = 4, fig.width = 12, fig.fullwidth = TRUE}
# Day 7
tsne_d7 <- 
  tsne_df %>%
  left_join(abun_d7, by = 'genome') %>% 
  ggplot(aes(x = tsne1, y = tsne2, color = order, size = abundance)) +
  geom_point(shape = 16, alpha = 0.8) +
  scale_color_manual(values = order_colors) +
  theme_minimal() +
  theme(legend.position = 'none')

# Day 21
tsne_d21 <- 
  tsne_df %>%
  left_join(abun_d21, by = 'genome') %>%
  ggplot(aes(x = tsne1, y = tsne2, color = order, size = abundance)) +
  geom_point(shape = 16, alpha = 0.8) +
  scale_color_manual(values = order_colors) +
  theme_minimal() +
  theme(legend.position = 'none')

# Day 35
tsne_d35 <- 
  tsne_df %>%
  left_join(abun_d35, by = 'genome') %>%
  ggplot(aes(x = tsne1, y = tsne2, color = order, size = abundance)) +
  geom_point(shape = 16, alpha = 0.8) +
  scale_color_manual(values = order_colors) +
  theme_minimal() +
  theme(legend.position = 'none')

grid.arrange(tsne_d7, tsne_d21, tsne_d35, ncol = 3)
```


## 7.3 - Compositional barplots (Fig. 2d)

### Compositional barplot at order level

```{r composition_by_order, comment = "", message = FALSE, warning = FALSE}
physeq_comp_rare_order <-
  aggregate_rare(
    phylo_seq,
    level = "order",
    detection = 0.01 / 100,
    prevalence = 50 / 100,
    include.lowest = TRUE
    )
  
phy_order_df <- 
  psmelt(physeq_comp_rare_order) %>%
  select(OTU, Sample, trial_age, Abundance) %>%
  rename(order = 'OTU') %>%
  separate_wider_delim(trial_age, "_", names = c("trial", "sampling_time"))
```

```{r oplot_order, comment = "", message = FALSE, warning = FALSE, fig.height = 4, fig.width = 9, fig.fullwidth = TRUE}
phy_order_df %>%
  mutate(Sample = str_remove(Sample, "_.*")) %>% 
  rename(Trial = 'Sample') %>% 
  mutate(order = factor(order, levels =  c('Veillonellales','Acidaminococcales',
                                           'Selenomonadales','UBA4068','UBA1212',
                                           'Monoglobales','Peptostreptococcales',
                                           'Monoglobales_A','Clostridiales',
                                           'Lachnospirales','Christensenellales',
                                           'TANB77','Oscillospirales','RFN20',
                                           'Bacillales','Acholeplasmatales',
                                           'Erysipelotrichales','ML615J-28',
                                           'Lactobacillales','RF39',
                                           'Deferribacterales','Actinomycetales',
                                           'Coriobacteriales','Gastranaerophilales',
                                           'Flavobacteriales','Bacteroidales',
                                           'Rs-D84','Burkholderiales','RF32',
                                           'Enterobacterales','Desulfovibrionales',
                                           'Verrucomicrobiales','Opitutales',
                                           'Victivallales','Methanomassiliicoccales',
                                           'Synergistales','Campylobacterales',
                                           'Saccharimonadales','Methanobacteriales',
                                           'Methanomicrobiales'))) %>%
    mutate(sampling_time = factor(sampling_time,
                                  levels = c("7", "21", "35"))) %>% 
    ggplot() +
  geom_bar(aes(x = Trial, y = Abundance, color = order, fill = order),
           stat = "identity", position = "stack") +
  facet_wrap(~sampling_time, scales = "free_x",
             labeller = as_labeller(c('7' = 'Day 7',
                                      '21' = 'Day 21',
                                      '35' = 'Day 35'))) +
  scale_color_manual('Order', values = order_colors) +
  scale_fill_manual('Order', values = order_colors) +
  ylab('Relative abundance') +
  xlab('Trial') +
  theme(panel.background = element_blank())
```

### Horizontal barplot (not in the Supplementary, but for a more detailed exploration)

```{r plot_horizontal, comment = "", message = FALSE, warning = FALSE, fig.height = 4, fig.width = 6, fig.fullwidth = TRUE}
phy_order_df %>%
  mutate(order = factor(order, 
                        levels = c('Veillonellales', 'Acidaminococcales',
                                   'Selenomonadales', 'UBA4068', 'UBA1212',
                                   'Monoglobales', 'Peptostreptococcales',
                                   'Monoglobales_A', 'Clostridiales',
                                   'Lachnospirales', 'Christensenellales',
                                   'TANB77', 'Oscillospirales', 'RFN20', 
                                   'Bacillales','Acholeplasmatales', 
                                   'Erysipelotrichales', 'ML615J-28', 
                                   'Lactobacillales','RF39','Deferribacterales',
                                   'Actinomycetales', 'Coriobacteriales',
                                   'Gastranaerophilales','Flavobacteriales',
                                   'Bacteroidales', 'Rs-D84', 'Burkholderiales',
                                   'RF32','Enterobacterales', 
                                   'Desulfovibrionales', 'Verrucomicrobiales',
                                   'Opitutales','Victivallales', 
                                   'Methanomassiliicoccales', 'Synergistales',
                                   'Campylobacterales','Saccharimonadales',
                                   'Methanobacteriales', 'Methanomicrobiales'))) %>%
  mutate(sampling_time = str_replace(sampling_time,
                                     pattern = "7",
                                     replacement = "Day 7"),
         sampling_time = str_replace(sampling_time,
                                     pattern = "21",
                                     replacement = "Day 21"),
         sampling_time = str_replace(sampling_time,
                                     pattern = "35",
                                     replacement = "Day 35")) %>%
  mutate(sampling_time = factor(sampling_time,
                                levels = c("Day 7", "Day 21", "Day 35"))) %>%
  ggplot(aes(x = Abundance, y = Sample,
             fill = order, group = order, color = order)) +
  geom_bar(stat = "identity", position = "stack", width = 1.1) +
  facet_nested(sampling_time * trial ~ ., scales = "free_y") +
  guides(fill = guide_legend(ncol = 1),
         color = guide_legend(ncol = 1)
         ) +
  scale_color_manual('Order', values = order_colors) +
  scale_fill_manual('Order', values = order_colors) +
  xlab('Relative abundance') +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_blank(),
        panel.spacing = unit(0.01, "lines"),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 10),
        strip.text = element_text(size = 8)) 
```

### Clean environment

```{r clean_7, comment = "", message = FALSE, warning = FALSE}
rm(list = ls())
```
